[package]
name = "swir"
version = "0.3.0"
authors = ["Dawid Nowak <nowakd@gmail.com>"]
repository = "https://github.com/swir-rs/swir"
readme = "README.md"
license = "Apache-2.0"
description = "Sidecar Written in Rust"
keywords = ["sidecar", "rest", "messaging","cloudcomputing","kafka","nats","grpc"]
categories = ["sidecar","messaging","kafka","nats","grpc","cloudcomputing"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5"
futures = "=0.3"
futures-core= "=0.3"
futures-util = "=0.3"
futures-executor = "=0.3"

log = "0.4"
env_logger = "0.7"
color-backtrace="*"
rand = "0.7"
base64 = "*"
multimap="0.8"
cfg-if = { version = "=0.1.10" }
custom_error= "1.7"
tokio = { version = "=0.2", features = ["full","sync"]}
tokio-tls = "0.3"
tokio-rustls = "0.13"
rustls = "0.17"
async-stream = "0.2"
hyper = "0.13"
http = "0.2"  
http-body = "0.3"
hostname= "0.3"
get_if_addrs = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_bytes = { version = "0.11"}
currenttimemillis = {version ="*", git = "https://github.com/swir-rs/currenttimemillis-rs"}
rdkafka = { version="0.23" } 
rdkafka-sys = { version = "1.3", default-features = false} 
nats = {version="*",optional=true}
rusoto_kinesis={ version="0.43"}
rusoto_dynamodb={ version="0.43"}
rusoto_signature={ version="0.43"}
rusoto_core={ version="0.43"}
aws-lock-client = {version="*", git="https://github.com/swir-rs/aws-lock-client-rs"} 
regex ="*"
lazy_static="*"
async-trait="*"
prost = "0.6"
prost-derive = "0.6"
tonic = {version="0.2", git ="https://github.com/swir-rs/tonic", optional=false, branch = "load_balancing_with_dynamic_discovery" }
config = { version="*", features = ["with_env_vars"],  git = "https://github.com/swir-rs/config-rs" }
redis = { version="0.15",features = ["cluster"]}

mdns-responder = {version="0.2", git = "https://github.com/swir-rs/rust-mdns"}

[build-dependencies]
tonic-build = { version="0.2", git ="https://github.com/swir-rs/tonic", branch = "load_balancing_with_dynamic_discovery"  }


[features]
with_nats = ["nats"]
