apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor2
  annotations:
    "sidecar.jaegertracing.io/inject": "true"  
  labels:
    app: swir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swir
  template:
    metadata:
      labels:
        app: swir
    spec:
      containers:
      - name: swir
        image: swir/swir:v3
        env:
          - name: swir_config_file
            value: /swir_config/config.yaml
        volumeMounts:
          - name: config-volume
            mountPath: /swir_config            
      - name: client
        image: swir-example-java-processor:v3
        env:
          - name: sidecar_url
            value: "http://127.0.0.1:8080"
          - name: subscribe_topic
            value: inventory
          - name: producer_topic
            value: billing
          - name: server_port
            value: "8090"
      volumes:
        - name: config-volume
          configMap:
            name: processor2-config
            items:
              - key: processor_2.yaml
                path: config.yaml
