ip: "0.0.0.0"
http_port: 8080
https_port: 8443
grpc_port: 50051
internal_grpc_port: 50052
tls_private_key: "/swir.CA.pem"
tls_certificate: "/demoCA/cacert.pem"
#client_executable: "client.jar"
pubsub:
  kafka: []
  nats: []
  aws_kinesis:
    - regions:
        - "eu-west-1"
      consumer_topics: []       
      producer_topics:
        - producer_topic: aws_processor_orders_blue
          client_topic: orders

stores:  
  redis: []
  dynamodb:
    - region: "eu-west-1"
      tables:
        - table_name: "swir-demo"
          client_name: "source_store"          

