AssociatePublicIpAddress: true
BlockDeviceMappings:
- DeviceName: /dev/xvdcz
  Ebs:
    DeleteOnTermination: true
    VolumeSize: 10
    VolumeType: gp2
EbsOptimized: false
IamInstanceProfile: arn:aws:iam::164450575887:instance-profile/ecsInstanceRole
ImageId: ami-0851c53aff84212c3
InstanceMonitoring:
  Enabled: true
InstanceType: t2.micro
LaunchConfigurationName: swir-demo-launch-configuration-GHZQWWRV4A
UserData: '#!/bin/bash

  echo ECS_CLUSTER=swir-demo-cluster-GHZQWWRV4A >> /etc/ecs/ecs.config;echo ECS_BACKEND_HOST=
  >> /etc/ecs/ecs.config;'
